Alias /gitweb /var/www/git
<Directory /var/www/git>
    Options +ExecCGI
    AddHandler cgi-script .cgi
    DirectoryIndex gitweb.cgi
    AllowOverride None
    Require all granted
</Directory>

Alias /gitdash /var/www/gitdash
<Directory /var/www/gitdash>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

Alias /api /var/www/gitapi
<Directory /var/www/gitapi>
    Options +ExecCGI
    AddHandler cgi-script .py
    DirectoryIndex api.py
    AllowOverride None
    Require all granted
    CGIPassAuth On
</Directory>

ScriptAlias /git/public/ /usr/libexec/git-core/git-http-backend/
<Location /git/public/>
    SetEnv GIT_PROJECT_ROOT /var/lib/git/public
    SetEnv GIT_HTTP_EXPORT_ALL
    Require all granted
</Location>

ScriptAlias /git/private/ /usr/libexec/git-core/git-http-backend/
<Location /git/private/>
    SetEnv GIT_PROJECT_ROOT /var/lib/git/private
    SetEnv GIT_HTTP_EXPORT_ALL
    AuthType Basic
    AuthName "Git Private Repository"
    AuthUserFile /etc/httpd/.htpasswd
    Require valid-user
</Location>
