$projectroot = "/var/lib/git/public";
$strict_export = 0;
%features = (
  'blame'   => { 'default' => [1] },
  'grep'    => { 'default' => [1] },
  'pickaxe' => { 'default' => [1] },
  'search'  => { 'default' => [1] },
);
